version: "3.8"
services:
  source:
    container_name: source
    build:
      context: .
    networks:
      - sourceNetwork
    environment:
      SERVICE_B_URL: http://destination:8081/mdns-entries
    entrypoint: /mdns-broadcast s

  destination:
    container_name: destination
    build:
      context: .
    networks:
      - destinationNetwork
    ports:
      - "8081:8081"
    entrypoint: /mdns-broadcast d

networks:
  sourceNetwork:
    name: sourceNetwork
    driver: bridge
  destinationNetwork:
    name: destinationNetwork
    driver: bridge
